name: semantic-release

on: [push]

jobs:
  semantic-release:
    
    runs-on: ubuntu-latest

    container:
      image: docker://node:latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: npm install semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/gitlab conventional-changelog -D

    - name: Launch semantic
      run: npx semantic-release -p --dry-run --branch update
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
