name: semantic-release

on: push

jobs:
  docker_image:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Add nodejs to PPA
      run: sudo apt-get install curl && curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    - name: Install plugins for semantic-release
      run: npm install semantic-release @semantic-release/{git,changelog,github} conventional-changelog -D
    - name: Launch semantic
      run: npx semantic-release -p