name: semantic-release

on: push

jobs:
  semantic-release:
    steps:
    - name: My first action
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v1
    - name: Install plugins for semantic-release
      run: npm install semantic-release @semantic-release/{git,changelog,gitlab} conventional-changelog -D
    - name: Launch semantic
      run: npx semantic-release -p
    container: 
      image: nodes:latest
      env:
        - GH_TOKEN: ${{ GH_TOKEN }}